// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5f_BBwv2pDvVGCbcWnU-pNmW6CpPvjPU',
    appId: '1:337371444056:web:d14dd34e83ef590e31ab2d',
    messagingSenderId: '337371444056',
    projectId: 'howzat-658e3',
    authDomain: 'howzat-658e3.firebaseapp.com',
    storageBucket: 'howzat-658e3.firebasestorage.app',
    measurementId: 'G-7BD3C5L5TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlfpPSX8gH0qRfBbaYKoIi69lmOC5OsG0',
    appId: '1:337371444056:android:c1123765d84e391231ab2d',
    messagingSenderId: '337371444056',
    projectId: 'howzat-658e3',
    storageBucket: 'howzat-658e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg8qMggUXwVVPSAqzOut7HpWyfatj5g3M',
    appId: '1:337371444056:ios:81d1463357d37d8a31ab2d',
    messagingSenderId: '337371444056',
    projectId: 'howzat-658e3',
    storageBucket: 'howzat-658e3.firebasestorage.app',
    iosBundleId: 'com.example.howzat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5f_BBwv2pDvVGCbcWnU-pNmW6CpPvjPU',
    appId: '1:337371444056:web:4cbc62d6320c5ecd31ab2d',
    messagingSenderId: '337371444056',
    projectId: 'howzat-658e3',
    authDomain: 'howzat-658e3.firebaseapp.com',
    storageBucket: 'howzat-658e3.firebasestorage.app',
    measurementId: 'G-HQQDL3LMGT',
  );

}